config/routes.rb
Rails.application.routes.draw do
  resources :signatures, except: [:edit, :update] do
    resources :invoices, module: :signatures, only: [:index]
    resource  :installment_book, module: :signatures, only: [:show]
  end

  resources :packages, except: [:destroy]
  resources :additional_services, except: [:destroy]
  resources :plans, except: [:destroy]
  resources :customers

  root "customers#index"
end

app/models/concerns/signature/billable.rb
module Signature::Billable
  extend ActiveSupport::Concern

  included do
    after_create :create_bills, :create_invoices, :create_installment_book_to_signature
  end

  private

    def create_bills
      return if bills.exists?

      create_bills_to plan || package
      additional_services.each { |service| create_bills_to service }
    end

    def create_bills_to item
      12.times { |date| bills.create(billable: item, due_date: created_at + date.month, price: item.price) }
    end

    def create_invoices
      12.times { |date| invoices.create(due_date: created_at + date.month, price: total_invoice_price) }
    end

    def total_invoice_price
      (plan&.price || package&.price) + additional_services.sum(&:price)
    end

    def create_installment_book_to_signature
      create_installment_book(due_date: Date.current + 1.month, price: invoices.first.price * 12)
    end
end

app/models/package.rb
class Package < ApplicationRecord
  belongs_to :plan

  has_and_belongs_to_many :additional_services
  has_many :signatures
  has_many :bills, as: :billable

  before_save :calculate_total_items, unless: -> { price.present? }

  private

    def calculate_total_items
      self.price = plan.price + additional_services.sum(&:price)
    end
end

app/models/signature.rb
class Signature < ApplicationRecord
  include Signature::Billable

  belongs_to :customer
  belongs_to :plan, optional: true
  belongs_to :package, optional: true

  has_and_belongs_to_many :additional_services
  has_many :invoices, dependent: :destroy
  has_many :bills, dependent: :destroy
  has_one  :installment_book, dependent: :destroy

  validate :should_have_package_or_plan, :should_not_duplicate_additional_services

  private

    def should_have_package_or_plan
      errors.add(:base, "Must have either a package or a plan, not both") unless has_plan_or_package?
    end

    def should_not_duplicate_additional_services
      errors.add(:base, "The chosen additional services are already in the package") if has_repeated_additional_services?
    end

    def has_repeated_additional_services?
      (package.additional_service_ids & additional_service_ids).any? if package.present?
    end

    def has_plan_or_package?
      plan.present? != package.present?
    end
end

app/models/signature/billable.rb
module Signature::Billable
  extend ActiveSupport::Concern

  included do
    after_create :generate_billing_data
  end

  private

    def generate_billing_data
      create_bills
      create_invoices
      create_installment_book_to_signature
    end

    def create_bills
      create_bills_to plan || package
      additional_services.each { |service| create_bills_to service }
    end

    def create_bills_to item
      12.times { |date| bills.create(billable: item, due_date: created_at + date.month, price: item.price) }
    end

    def create_invoices
      12.times { |date| invoices.create(due_date: created_at + date.month, price: total_invoice_price) }
    end

    def total_invoice_price
      (plan&.price || package&.price) + additional_services.sum(&:price)
    end

    def create_installment_book_to_signature
      create_installment_book(due_date: Date.current + 1.month, price: invoices.first.price * 12)
    end
end

app/controllers/signatures/bills_controller.rb
class Signatures::BillsController < ApplicationController
  before_action :set_signature

  def index
    @packages_bills = @signature.package.bills if @signature.package.present?
    @plan_bills = @signature.plan.bills if @signature.plan.present?

    @additional_services = @signature.additional_services
  end

  private

    def set_signature
      @signature = Signature.find(params[:signature_id])
    end
end

app/controllers/signatures/installment_books_controller.rb
class Signatures::InstallmentBooksController < ApplicationController
  before_action :set_signature

  def show
    @installment_book = @signature.installment_book
  end

  private

    def set_signature
      @signature = Signature.find(params[:signature_id])
    end
end

app/controllers/signatures/invoices_controller.rb
class Signatures::InvoicesController < ApplicationController
  before_action :set_signature

  def index
    @package_bills = @signature.package&.bills
    @plan_bills = @signature.plan&.bills
    @additional_services = @signature.additional_services
  end

  private

    def set_signature
      @signature = Signature.find(params[:signature_id])
    end
end

app/controllers/signatures_controller.rb
class SignaturesController < ApplicationController
  before_action :set_signature, only: %i[ show destroy ]

  def index
    @signatures = Signature.all
  end

  def show
  end

  def new
    @signature = Signature.new
  end

  def create
    @signature = Signature.new(signature_params)

    if @signature.save
      redirect_to @signature, notice: "Signature was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @signature.destroy!
    redirect_to signatures_path, notice: "Signature was successfully destroyed.", status: :see_other
  end

  private

    def set_signature
      @signature = Signature.find(params.expect(:id))
    end

    def signature_params
      params.expect(signature: [ :customer_id, :plan_id, :package_id, additional_service_ids: [] ])
    end
end

app/helpers/signatures_helper.rb
module SignaturesHelper
end

app/views/signatures/_form.html.erb
<%= form_with(model: signature, class: "contents") do |form| %>
  <% if signature.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-md mt-3">
      <h2><%= pluralize(signature.errors.count, "error") %> prohibited this signature from being saved:</h2>

      <ul class="list-disc ml-6">
        <% signature.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :customer_id, "Customer" %>
    <%= form.collection_select :customer_id, Customer.all, :id, :name, {}, required: true, class: [ "w-full px-3 py-2 border rounded-md shadow-sm focus:ring-2 focus:ring-offset-2 transition-colors duration-200", {"border-gray-400 focus:outline-blue-600": signature.errors[:price].none?, "border-red-400 focus:outline-red-600": signature.errors[:price].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :plan_id, "Plan", class: "block text-sm font-medium text-gray-700 mb-2" %>
    <%= form.collection_select :plan_id, Plan.all, :id, :name, {prompt: "Plans"}, class: [ "w-full px-3 py-2 border rounded-md shadow-sm focus:ring-2 focus:ring-offset-2 transition-colors duration-200", {"border-gray-400 focus:outline-blue-600": signature.errors[:price].none?, "border-red-400 focus:outline-red-600": signature.errors[:price].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :package_id, "Package", class: "block text-sm font-medium text-gray-700 mb-2" %>
    <%= form.collection_select :package_id, Package.all, :id, :name, {prompt: "Package"}, class: [ "w-full px-3 py-2 border rounded-md shadow-sm focus:ring-2 focus:ring-offset-2 transition-colors duration-200", {"border-gray-400 focus:outline-blue-600": signature.errors[:price].none?, "border-red-400 focus:outline-red-600": signature.errors[:price].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :additional_service_ids, "Additional services",class: "block text-sm font-medium text-gray-700 mb-2" %>
    <%= form.collection_select :additional_service_ids, AdditionalService.all, :id, :name, {prompt: "Additional services"}, multiple: true, class: [ "w-full px-3 py-2 border rounded-md shadow-sm focus:ring-2 focus:ring-offset-2 transition-colors duration-200", {"border-gray-400 focus:outline-blue-600": signature.errors[:price].none?, "border-red-400 focus:outline-red-600": signature.errors[:price].any?}] %>
  </div>

  <div class="inline">
    <%= form.submit class: "w-full sm:w-auto rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/signatures/_signature.html.erb
<div id="<%= dom_id signature %>" class="w-full sm:w-auto my-5 space-y-5">
  <div>
    <strong class="block font-medium mb-1">Customer:</strong>
    <%= signature.customer.name %>
  </div>

  <div>
    <strong class="block font-medium mb-1">Plan:</strong>
    <%= signature.plan&.name %>
  </div>

  <div>
    <strong class="block font-medium mb-1">Package:</strong>
    <%= signature.package&.name %>
  </div>

  <div>
    <strong class="block font-medium mb-1">Additionals services:</strong>
    <ul class="ms-4 mb-4 list-disc">
      <% signature.additional_services.each do |additional_service| %>
        <li><%= additional_service.name %></li>
      <% end %>
    </ul>
  </div>
</div>

app/views/signatures/index.html.erb
<% content_for :title, "Signatures" %>

<div class="w-full">
  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Signatures</h1>
    <%= link_to "New signature", new_signature_path, class: "rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white block font-medium" %>
  </div>

  <div id="signatures" class="min-w-full divide-y divide-gray-200 space-y-5">
    <% if @signatures.any? %>
      <% @signatures.each do |signature| %>
        <div class="flex flex-col sm:flex-row justify-between items-center pb-5 sm:pb-0">
          <%= render signature %>
          <div class="w-full sm:w-auto flex flex-col sm:flex-row space-x-2 space-y-2">
            <%= link_to "Invoices", signature_invoices_path(signature), class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
            <%= link_to "Installment_book", signature_installment_book_path(signature), class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
            <%= link_to "Show", signature, class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
            <%= button_to "Destroy", signature, method: :delete, class: "w-full sm:w-auto rounded-md px-3.5 py-2.5 text-white bg-red-600 hover:bg-red-500 font-medium cursor-pointer", data: { turbo_confirm: "Are you sure?" } %>
          </div>
        </div>
      <% end %>
    <% else %>
      <p class="text-center my-10">No signatures found.</p>
    <% end %>
  </div>
</div>

app/views/signatures/new.html.erb
<% content_for :title, "New signature" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New signature</h1>

  <%= render "form", signature: @signature %>

  <%= link_to "Back to signatures", signatures_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/signatures/show.html.erb
<% content_for :title, "Showing signature" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Showing signature</h1>

  <%= render @signature %>

  <%= link_to "Back to signatures", signatures_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= button_to "Destroy this signature", @signature, method: :delete, form_class: "sm:inline-block mt-2 sm:mt-0 sm:ml-2", class: "w-full rounded-md px-3.5 py-2.5 text-white bg-red-600 hover:bg-red-500 font-medium cursor-pointer", data: { turbo_confirm: "Are you sure?" } %>
</div>