config/routes.rb
Rails.application.routes.draw do
  resources :signatures, except: [:edit, :update] do
    resources :invoices, module: :signatures, only: [:index]
    resource  :installment_book, module: :signatures, only: [:show]
  end

  resources :packages, except: [:destroy]
  resources :additional_services, except: [:destroy]
  resources :plans, except: [:destroy]
  resources :customers

  root "customers#index"
end

app/models/additional_service.rb
class AdditionalService < ApplicationRecord
  has_and_belongs_to_many :packages
  has_and_belongs_to_many :signatures

  has_many :bills, as: :billable
end

app/controllers/additional_services_controller.rb
class AdditionalServicesController < ApplicationController
  before_action :set_additional_service, only: %i[ show edit update ]

  def index
    @additional_services = AdditionalService.all
  end

  def show
  end

  def new
    @additional_service = AdditionalService.new
  end

  def edit
  end

  def create
    @additional_service = AdditionalService.create!(additional_service_params)
    redirect_to @additional_service, notice: "Additional service was successfully created."
  end

  def update
    @additional_service.update!(additional_service_params)
    redirect_to @additional_service, notice: "Additional service was successfully updated."
  end

  private

    def set_additional_service
      @additional_service = AdditionalService.find(params.expect(:id))
    end

    def additional_service_params
      params.expect(additional_service: [ :name, :price ])
    end
end

app/helpers/additional_services_helper.rb
module AdditionalServicesHelper
end

app/views/additional_services/_additional_service.html.erb
<div id="<%= dom_id additional_service %>" class="w-full sm:w-auto my-5 space-y-5">
  <div>
    <strong class="block font-medium mb-1">Name:</strong>
    <%= additional_service.name %>
  </div>
  <div>
    <strong class="block font-medium mb-1">Price:</strong>
    <%= additional_service.price %>
  </div>
</div>

app/views/additional_services/_form.html.erb
<%= form_with(model: additional_service, class: "contents") do |form| %>
  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, required: true, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": additional_service.errors[:name].none?, "border-red-400 focus:outline-red-600": additional_service.errors[:name].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :price %>
    <%= form.number_field :price, required: true, min: 0, step: "any", class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": additional_service.errors[:price].none?, "border-red-400 focus:outline-red-600": additional_service.errors[:price].any?}] %>
  </div>

  <div class="inline">
    <%= form.submit class: "w-full sm:w-auto rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/additional_services/edit.html.erb
<% content_for :title, "Editing additional service" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing additional service</h1>

  <%= render "form", additional_service: @additional_service %>

  <%= link_to "Show this additional service", @additional_service, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to additional services", additional_services_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/additional_services/index.html.erb
<% content_for :title, "Additional services" %>

<div class="w-full">
  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Additional services</h1>
    <%= link_to "New additional service", new_additional_service_path, class: "rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white block font-medium" %>
  </div>

  <div id="additional_services" class="min-w-full divide-y divide-gray-200 space-y-5">
    <% if @additional_services.any? %>
      <% @additional_services.each do |additional_service| %>
        <div class="flex flex-col sm:flex-row justify-between items-center pb-5 sm:pb-0">
          <%= render additional_service %>
          <div class="w-full sm:w-auto flex space-x-2">
            <%= link_to "Show", additional_service, class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
            <%= link_to "Edit", edit_additional_service_path(additional_service), class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
          </div>
        </div>
      <% end %>
    <% else %>
      <p class="text-center my-10">No additional services found.</p>
    <% end %>
  </div>
</div>

app/views/additional_services/new.html.erb
<% content_for :title, "New additional service" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New additional service</h1>

  <%= render "form", additional_service: @additional_service %>

  <%= link_to "Back to additional services", additional_services_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/additional_services/show.html.erb
<% content_for :title, "Showing additional service" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Showing additional service</h1>

  <%= render @additional_service %>

  <%= link_to "Edit this additional service", edit_additional_service_path(@additional_service), class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to additional services", additional_services_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>