config/routes.rb
Rails.application.routes.draw do
  resources :signatures, except: [:edit, :update] do
    resources :invoices, module: :signatures, only: [:index]
    resource  :installment_book, module: :signatures, only: [:show]
  end

  resources :packages, except: [:destroy]
  resources :additional_services, except: [:destroy]
  resources :plans, except: [:destroy]
  resources :customers

  root "customers#index"
end

app/models/plan.rb
class Plan < ApplicationRecord
  has_many :packages
  has_many :signatures
  has_many :bills, as: :billable
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  before_action :set_plan, only: %i[ show edit update ]

  def index
    @plans = Plan.all
  end

  def show
  end

  def new
    @plan = Plan.new
  end

  def edit
  end

  def create
    @plan = Plan.create!(plan_params)
    redirect_to @plan, notice: "Plan was successfully created."
  end

  def update
    @plan.update!(plan_params)
    redirect_to @plan, notice: "Plan was successfully updated."
  end

  private

    def set_plan
      @plan = Plan.find(params.expect(:id))
    end

    def plan_params
      params.expect(plan: [ :name, :price ])
    end
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/views/plans/_form.html.erb
<%= form_with(model: plan, class: "contents") do |form| %>
  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, required: true, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": plan.errors[:name].none?, "border-red-400 focus:outline-red-600": plan.errors[:name].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :price %>
    <%= form.number_field :price, required: true, min: 0, step: "any", class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": plan.errors[:price].none?, "border-red-400 focus:outline-red-600": plan.errors[:price].any?}] %>
  </div>

  <div class="inline">
    <%= form.submit class: "w-full sm:w-auto rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/plans/_plan.html.erb
<div id="<%= dom_id plan %>" class="w-full sm:w-auto my-5 space-y-5">
  <div>
    <strong class="block font-medium mb-1">Name:</strong>
    <%= plan.name %>
  </div>
  <div>
    <strong class="block font-medium mb-1">Price:</strong>
    <%= plan.price %>
  </div>
</div>

app/views/plans/edit.html.erb
<% content_for :title, "Editing plan" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing plan</h1>

  <%= render "form", plan: @plan %>

  <%= link_to "Show this plan", @plan, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to plans", plans_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/plans/index.html.erb
<% content_for :title, "Plans" %>

<div class="w-full">
  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Plans</h1>
    <%= link_to "New plan", new_plan_path, class: "rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white block font-medium" %>
  </div>

  <div id="plans" class="min-w-full divide-y divide-gray-200 space-y-5">
    <% if @plans.any? %>
      <% @plans.each do |plan| %>
        <div class="flex flex-col sm:flex-row justify-between items-center pb-5 sm:pb-0">
          <%= render plan %>
          <div class="w-full sm:w-auto flex space-x-2">
            <%= link_to "Show", plan, class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
            <%= link_to "Edit", edit_plan_path(plan), class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
          </div>
        </div>
      <% end %>
    <% else %>
      <p class="text-center my-10">No plans found.</p>
    <% end %>
  </div>
</div>

app/views/plans/new.html.erb
<% content_for :title, "New plan" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New plan</h1>

  <%= render "form", plan: @plan %>

  <%= link_to "Back to plans", plans_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/plans/show.html.erb
<% content_for :title, "Showing plan" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Showing plan</h1>

  <%= render @plan %>

  <%= link_to "Edit this plan", edit_plan_path(@plan), class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to plans", plans_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>