config/routes.rb
Rails.application.routes.draw do
  resources :signatures, except: [:edit, :update] do
    resources :invoices, module: :signatures, only: [:index]
    resource  :installment_book, module: :signatures, only: [:show]
  end

  resources :packages, except: [:destroy]
  resources :additional_services, except: [:destroy]
  resources :plans, except: [:destroy]
  resources :customers

  root "customers#index"
end

app/models/additional_service.rb
class AdditionalService < ApplicationRecord
  has_and_belongs_to_many :packages
  has_and_belongs_to_many :signatures

  has_many :bills, as: :billable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bill.rb
class Bill < ApplicationRecord
  belongs_to :billable, polymorphic: true
  belongs_to :signature
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :signatures, dependent: :destroy
end

app/models/installment_book.rb
class InstallmentBook < ApplicationRecord
  belongs_to :signature
end

app/models/invoice.rb
class Invoice < ApplicationRecord
  belongs_to :signature
end

app/models/package.rb
class Package < ApplicationRecord
  belongs_to :plan

  has_and_belongs_to_many :additional_services
  has_many :signatures
  has_many :bills, as: :billable

  before_save :calculate_total_items, unless: -> { price.present? }

  private

    def calculate_total_items
      self.price = plan.price + additional_services.sum(&:price)
    end
end

app/models/plan.rb
class Plan < ApplicationRecord
  has_many :packages
  has_many :signatures
  has_many :bills, as: :billable
end

app/models/signature.rb
class Signature < ApplicationRecord
  include Signature::Billable

  belongs_to :customer
  belongs_to :plan, optional: true
  belongs_to :package, optional: true

  has_and_belongs_to_many :additional_services
  has_many :invoices, dependent: :destroy
  has_many :bills, dependent: :destroy
  has_one  :installment_book, dependent: :destroy

  validate :should_have_package_or_plan, :should_not_duplicate_additional_services

  private

    def should_have_package_or_plan
      errors.add(:base, "Must have either a package or a plan, not both") unless has_plan_or_package?
    end

    def should_not_duplicate_additional_services
      errors.add(:base, "The chosen additional services are already in the package") if has_repeated_additional_services?
    end

    def has_repeated_additional_services?
      (package.additional_service_ids & additional_service_ids).any? if package.present?
    end

    def has_plan_or_package?
      plan.present? != package.present?
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: %i[ show edit update destroy ]

  def index
    @customers = Customer.all
  end

  def show
  end

  def new
    @customer = Customer.new
  end

  def edit
  end

  def create
    @customer = Customer.create!(customer_params)
    redirect_to @customer, notice: "Customer was successfully created."
  end

  def update
    @customer.update!(customer_params)
    redirect_to @customer, notice: "Customer was successfully updated."
  end

  def destroy
    @customer.destroy!
    redirect_to customers_path, notice: "Customer was successfully destroyed.", status: :see_other
  end

  private

    def set_customer
      @customer = Customer.find(params.expect(:id))
    end

    def customer_params
      params.expect(customer: [ :name, :age ])
    end
end

app/controllers/packages_controller.rb
class PackagesController < ApplicationController
  before_action :set_package, only: %i[ show edit update ]

  def index
    @packages = Package.all
  end

  def show
  end

  def new
    @package = Package.new
  end

  def edit
  end

  def create
    @package = Package.create!(package_params)
    redirect_to @package, notice: "Package was successfully created."
  end

  def update
    @package.update!(package_params)
    redirect_to @package, notice: "Package was successfully updated."
  end

  private

    def set_package
      @package = Package.find(params.expect(:id))
    end

    def package_params
      params.expect(package: [ :name, :price, :plan_id, additional_service_ids: [] ])
    end
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  before_action :set_plan, only: %i[ show edit update ]

  def index
    @plans = Plan.all
  end

  def show
  end

  def new
    @plan = Plan.new
  end

  def edit
  end

  def create
    @plan = Plan.create!(plan_params)
    redirect_to @plan, notice: "Plan was successfully created."
  end

  def update
    @plan.update!(plan_params)
    redirect_to @plan, notice: "Plan was successfully updated."
  end

  private

    def set_plan
      @plan = Plan.find(params.expect(:id))
    end

    def plan_params
      params.expect(plan: [ :name, :price ])
    end
end

app/controllers/signatures_controller.rb
class SignaturesController < ApplicationController
  before_action :set_signature, only: %i[ show destroy ]

  def index
    @signatures = Signature.all
  end

  def show
  end

  def new
    @signature = Signature.new
  end

  def create
    @signature = Signature.new(signature_params)

    if @signature.save
      redirect_to @signature, notice: "Signature was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @signature.destroy!
    redirect_to signatures_path, notice: "Signature was successfully destroyed.", status: :see_other
  end

  private

    def set_signature
      @signature = Signature.find(params.expect(:id))
    end

    def signature_params
      params.expect(signature: [ :customer_id, :plan_id, :package_id, additional_service_ids: [] ])
    end
end

app/helpers/additional_services_helper.rb
module AdditionalServicesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/packages_helper.rb
module PackagesHelper
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/helpers/signatures_helper.rb
module SignaturesHelper
end

app/views/layouts/_messages.html.erb
      <% if notice.present? %>
        <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
      <% end %>

      <% if alert.present? %>
        <p class="py-2 px-3 bg-red-50 mb-5 text-red-500 font-medium rounded-md inline-block" id="alert"><%= alert %></p>
      <% end %>

app/views/layouts/_navbar.html.erb
<nav class="bg-white shadow-md">
  <div class="container mx-auto px-4">
    <div class="flex items-center h-16">
      <div class="flex items-baseline space-x-2 flex-wrap">
        <%= link_to "Customers", customers_path, class: "px-3 py-2 font-medium" %>
        <%= link_to "Signatures", signatures_path, class: "text-gray-600 px-3 py-2 font-medium" %>
        <%= link_to "Packages", packages_path, class: "text-gray-600 px-3 py-2 font-medium" %>
        <%= link_to "Plans", plans_path, class: "text-gray-600 px-3 py-2 font-medium" %>
        <%= link_to "Additional services", additional_services_path, class: "text-gray-600 px-3 py-2 font-medium" %>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Subscription Tv System" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "layouts/navbar" %>

    <main class="container mx-auto mt-28 px-5">
      <%= render "layouts/messages" %>

      <div class="flex">
        <%= yield %>
      </div>
    </main>
  </body>
</html>